services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle
    expose:
      - 3306
      - 33060
    ports:
      - 3306:3306
  moodle:
    depends_on:
       - db
    build: .git
    restart: always
    ports:
      - 80:80
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      -  ./moodledata:/var/www/moodledata
      -  ./moodle:/var/www/html
volumes:
  db_data:
